// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function isReference(_withReference) {
  return ("$ref" in _withReference);
}

function classify(withRef) {
  if (isReference(withRef)) {
    return {
            TAG: "Reference",
            _0: withRef
          };
  } else {
    return {
            TAG: "Object",
            _0: withRef
          };
  }
}

var WithReference = {
  isReference: isReference,
  classify: classify
};

function isReference$1(_withReference) {
  return ("$ref" in _withReference);
}

function classify$1(withRef) {
  if (isReference$1(withRef)) {
    return {
            TAG: "Reference",
            _0: withRef
          };
  } else {
    return {
            TAG: "Object",
            _0: withRef
          };
  }
}

var WithReference$1 = {
  isReference: isReference$1,
  classify: classify$1
};

var Mutable = {
  WithReference: WithReference$1
};

exports.WithReference = WithReference;
exports.Mutable = Mutable;
/* No side effect */
